### ISSUE TITLE
Error Loading Shared Libraries: libYARP_init.so.3 Not Found

### ISSUE THREAD

**Issue by saratrajput** [event-driven-robotics/four-dof-affine-tracking#2]
Hello. Thank you for providing the code. I followed the steps in the README using docker, but encountered the following error when running the algorithm:
```
shape_position --eros_k 11 --eros_d 0.6 --shape_file /usr/local/src/affine2dtracking/shapes/star.png
```
**Error message**:
```
shape_position: error while loading shared libraries: libYARP_init.so.3: cannot open shared object file: No such file or directory
```
I would appreciate guidance on resolving this shared library issue, including any steps I might have missed during installation or setup that could prevent such errors. Thank you in advance for your assistance.

**Comment by lunagava** [comment]
Hello @saratrajput 
I have just tested the installation from scratch. I realized there were some missing parts in the docker installation and some wrong linking paths in the code that I have fixed. 
I added more info in the README.md and a sample dataset to run the tracking directly from docker. 

I did not get your error message. It could be because you did not start the yarpserver.

Please follow the guide again and tell me if the latest update fixes the problem.

**Comment by saratrajput** [comment]
Hello @lunagava. Thank you for your reply and updating the README.

I had a question about where to run the `yarpserver` command. When running it in one of the terminals inside the container, I still get the same error for `shape_position`.

Please find the screen-shot of the terminals attached here:
![image](https://github.com/event-driven-robotics/four-dof-affine-tracking/assets/29677848/092de62b-61c8-4637-891e-069db1fb2bf1)
All the terminals are attached to the `affine:latest` container.

**Comment by saratrajput** [comment]
Hi @lunagava . I was able to figure out the problem. If I launch the shape_position algorithm from the build folder as:
```
./shape_position --eros_k 11 --eros_d 0.6 --shape_file /usr/local/src/four-dof-affine-tracking/shapes/star.png
```
I no longer get the error.

**Comment by lunagava** [comment]
Thanks for letting me know <3 Feel free to contact me if you have any other issues
